### ISSUE TITLE
result is IE 

### ISSUE THREAD

**Issue by bedroomteam** [openjudge/sandbox#14]
just demonstrate  the demo . please help me! Thanks!

log : 

debug> calling: global_init()
debug> blocked reserved signals
debug> created the manager thread at 0x419406
debug> leaving: global_init()
debug> calling: sandbox_init(0x7fffa4a458e0,0x7fffa4b27420)
debug> calling: sandbox_manager(0x51e750)
debug> sandbox_init() acquired lock (exclusive)
debug> calling: __sandbox_task_init(0x7fffa4a458e8,0x7fffa4b27420)
debug> manager broadcasting at 100.00Hz
debug> SP=10.00 / Kp=0.75, Ki=0.25, Kd=0.00 / MV=[5.00, 10.00]
debug> manager beacon (000001): PV=10.00 / P=0.00, I=0.00, D=0.00 / MV=10.00
debug> leaving: __sandbox_task_init()
debug> calling: __sandbox_stat_init(0x7fffa4ae6920)
debug> leaving: __sandbox_stat_init()
debug> calling: __sandbox_ctrl_init(0x7fffa4ae69c0,0x418b4a)
debug> leaving: __sandbox_ctrl_init()
debug> calling: __sandbox_ctrl_add_monitor(0x7fffa4ae69c0,0x412683)
debug> leaving: __sandbox_ctrl_add_monitor() = 0
debug> calling: __sandbox_ctrl_add_monitor(0x7fffa4ae69c0,0x40a4fc)
debug> leaving: __sandbox_ctrl_add_monitor() = 1
debug> result: PD
debug> status: PRE
debug> sandbox_init() released lock
debug> leaving: sandbox_init() = 0
debug> calling: sandbox_check(0x7fffa4a458e0)
debug> sandbox_check() acquired lock (exclusive)
debug> passed sandbox status check
debug> result: PD
debug> status: PRE
debug> calling: __sandbox_task_check(0x7fffa4a458e8)
debug> passed user identity test
debug> passed group identity test
debug> passed set{uid,gid} privilege test
debug> passed permission test of the targeted program
debug> passed jail validity test
debug> passed input channel validity test
debug> passed output channel validity test
debug> passed error channel validity test
debug> leaving: __sandbox_task_check() = 1
debug> passed task spec validation
debug> passed ctrl tracer validation
debug> passed ctrl monitor validation
debug> status: RDY
debug> sandbox_check() released lock
debug> leaving: sandbox_check() = 1
debug> calling: sandbox_execute(0x7fffa4a458e0)
debug> calling: sandbox_check(0x7fffa4a458e0)
debug> sandbox_check() acquired lock (exclusive)
debug> passed sandbox status check
debug> result: PD
debug> status: PRE
debug> calling: __sandbox_task_check(0x7fffa4a458e8)
debug> passed user identity test
debug> passed group identity test
debug> passed set{uid,gid} privilege test
debug> passed permission test of the targeted program
debug> passed jail validity test
debug> passed input channel validity test
debug> passed output channel validity test
debug> passed error channel validity test
debug> leaving: __sandbox_task_check() = 1
debug> passed task spec validation
debug> passed ctrl tracer validation
debug> passed ctrl monitor validation
debug> status: RDY
debug> sandbox_check() released lock
debug> leaving: sandbox_check() = 1
debug> sandbox_execute() acquired lock (exclusive)
debug> created: monitor thread #1 at 0x412683
debug> entering: the prisoner process
debug> created: monitor thread #2 at 0x40a4fc
debug> created: 2 monitor threads
debug> sandbox_execute() released lock
debug> forked the prisoner process as pid 12053
debug> result: PD
debug> status: BLK
debug> sandbox_execute() released lock
debug> calling: __sandbox_task_execute(0x7fffa4a458e8)
debug> calling: sandbox_tracer(0x7fffa4a458e0)
debug> registered sandbox 0x7fffa4a458e0 to the pool
debug> waiting for new trace option
debug> calling: sandbox_profiler(0x7fffa4a458e0)
debug> sandbox_profiler() acquired lock (shared)
debug> sandbox_profiler() released lock
debug> sandbox_profiler() acquired lock (shared)
debug> calling: proc_bind(0x7fffa4a458e0,0x42ba8fd0)
debug> leaving: proc_bind() = 1
debug> sandbox_profiler() released lock
debug> [WARNING] failed to get the prisoner's cpu clock id: 0 (Success)
debug> sandbox_profiler() acquired lock (exclusive)
debug> sandbox_profiler() released lock
debug> leaving: sandbox_profiler() = 0x7fffa4a458e4
debug> calling: sandbox_watcher(0x7fffa4a458e0)
debug> sandbox_watcher() acquired lock (shared)
debug> sandbox_watcher() released lock
debug> sandbox_watcher() acquired lock (shared)
debug> calling: proc_bind(0x7fffa4a458e0,0x4160ffc0)
debug> leaving: proc_bind() = 1
debug> sandbox_watcher() released lock
debug> ---------------------------------------------------------------
debug> waitid(1,12053,0x4160ff30,6): 0
debug> sandbox_watcher() acquired lock (exclusive)
debug> status: BLK
debug> sandbox_watcher() released lock
debug> calling: proc_probe(12053,4,0x4160ffc0)
debug> calling: check_procfs(12053)
debug> leaving: check_procfs() = 0
debug> [WARNING] procfs entries missing or invalid: 3 (No such process)
debug> leaving: proc_probe() = 0
debug> [WARNING] failed to probe process: 12053: 3 (No such process)
debug> sandbox_watcher() acquired lock (shared)
debug> sandbox_watcher() released lock
debug> wait: signaled (9)
debug> sandbox_watcher() acquired lock (exclusive)
debug> sandbox_watcher() released lock
debug> sandbox_watcher() acquired lock (exclusive)
debug> sandbox_watcher() released lock
debug> calling: __sandbox_stat_update(0x7fffa4a458e0,0x4160ffc0)
debug> __sandbox_stat_update() acquired lock (exclusive)
debug> __sandbox_stat_update() released lock
debug> __sandbox_stat_update() acquired lock (shared)
debug> __sandbox_stat_update() released lock
debug> __sandbox_stat_update() acquired lock (shared)
debug> __sandbox_stat_update() released lock
debug> __sandbox_stat_update() acquired lock (shared)
debug> __sandbox_stat_update() released lock
debug> leaving: __sandbox_stat_update()
debug> sandbox_watcher() acquired lock (shared)
debug> detected: event ERROR {0 0 0 0 0 0 0}
debug> calling: sandbox_default_policy(0x7fffa4ae7318,0x7fffa4ae6a88,0x7fffa4ae69c8)
debug> leaving: sandbox_default_policy()
debug> policy decided action: KILL {8 0}
debug> sandbox_watcher() released lock
debug> sandbox_watcher() acquired lock (exclusive)
debug> result: IE
debug> calling: trace_kill(0x4160ffc0,9)
debug> calling: proc_probe(12053,3,0x4160fac0)
debug> calling: check_procfs(12053)
debug> leaving: check_procfs() = 0
debug> [WARNING] procfs entries missing or invalid: 3 (No such process)
debug> leaving: proc_probe() = 0
debug> [WARNING] failed to probe process: 12053: 3 (No such process)
debug> leaving: trace_kill() = 0
debug> sandbox_watcher() released lock
debug> sandbox_watcher() acquired lock (shared)
debug> sandbox_watcher() released lock
debug> calling: trace_next(0x4160ffc0,1)
debug> calling: __trace(3,0x4160ffc0,(nil),0x4160fca8)
debug> obtained trace slot
debug> requesting trace option: NEXT
debug> received trace option: NEXT
debug> calling: __trace_impl(3,0x4160ffc0,(nil),0x51e738)
debug> leaving: __trace_impl() = -1
debug> sending trace option: ACK
debug> collected trace results
debug> released trace slot
debug> leaving: __trace() = -1
debug> leaving: trace_next() = 0
debug> sent trace option: ACK
debug> waiting for new trace option
debug> [WARNING] failed to schedule next watch: 0 (Success)
debug> sandbox_watcher() acquired lock (exclusive)
debug> sandbox_watcher() released lock
debug> sandbox_watcher() acquired lock (shared)
debug> exiting the watching loop
debug> sandbox_watcher() released lock
debug> sandbox_watcher() acquired lock (exclusive)
debug> status: FIN
debug> sandbox_watcher() released lock
debug> sandbox_watcher() acquired lock (exclusive)
debug> sandbox_watcher() released lock
debug> calling: trace_end(0x4160ffc0)
debug> calling: __trace(2,0x4160ffc0,(nil),(nil))
debug> obtained trace slot
debug> requesting trace option: END
debug> received trace option: END
debug> calling: __trace_impl(2,0x4160ffc0,(nil),0x51e738)
debug> leaving: __trace_impl() = 0
debug> sending trace option: ACK
debug> collected trace results
debug> released trace slot
debug> leaving: __trace() = 0
debug> sent trace option: ACK
debug> leaving: trace_end() = 1
debug> leaving: sandbox_watcher() = 0x7fffa4a458e4
debug> removed sandbox 0x7fffa4a458e0 from the pool
debug> leaving: sandbox_tracer() = 0x7fffa4a458e4
debug> joined 2 of 2 monitor threads
debug> leaving: sandbox_execute() = 0x7fffa4a458e4
result: IE
cpu: 0ms
mem: 0kB
debug> calling: sandbox_fini(0x7fffa4a458e0)
debug> sandbox_fini() acquired lock (exclusive)
debug> result: PD
debug> status: FIN
debug> calling: __sandbox_task_fini(0x7fffa4a458e8)
debug> leaving: __sandbox_task_fini()
debug> calling: __sandbox_stat_fini(0x7fffa4ae6920)
debug> leaving: __sandbox_stat_fini()
debug> calling: __sandbox_ctrl_fini(0x7fffa4ae69c0)
debug> leaving: __sandbox_ctrl_fini()
debug> sandbox_fini() released lock
debug> leaving: sandbox_fini() = 0
debug> calling: global_fini()
debug> leaving: sandbox_manager() = 0x51e750
debug> joined the manager thread
debug> flushed all pending signals
debug> restored old signal mask
debug> leaving: global_fini()

**Comment by bedroomteam** [comment]
why closed?

**Comment by liuyu81** [comment]
issues #14 and #15 are duplicated
