### ISSUE TITLE
libsandbox returning verdict 7

### ISSUE THREAD

**Issue by shubham-mulay-BR** [openjudge/sandbox#18]
I am using this judge and libsandbox, it is returning verdict 7,can you please tell me what is it? And along with it please give all the verdicts returned by sandbox.

**Comment by liuyu81** [comment]
did you mean the result code evaluates to `7`? here is the comprehensive list of result codes taken from `libsandbox/src/sandbox.h`

```
typedef enum
{
    S_RESULT_PD        =  0,    /*!< Pending */
    S_RESULT_OK        =  1,    /*!< Okay */
    S_RESULT_RF        =  2,    /*!< Restricted Function */
    S_RESULT_ML        =  3,    /*!< Memory Limit Exceed */
    S_RESULT_OL        =  4,    /*!< Output Limit Exceed */
    S_RESULT_TL        =  5,    /*!< Time Limit Exceed */
    S_RESULT_RT        =  6,    /*!< Run Time Error (SIGSEGV, SIGFPE, ...) */
    S_RESULT_AT        =  7,    /*!< Abnormal Termination */
    S_RESULT_IE        =  8,    /*!< Internal Error (of sandbox executor) */
    S_RESULT_BP        =  9,    /*!< Bad Policy (since 0.3.3) */
    S_RESULT_R0        = 10,    /*!< Reserved result type 0 (since 0.3.2) */
    S_RESULT_R1        = 11,    /*!< Reserved result type 1 (since 0.3.2) */
    S_RESULT_R2        = 12,    /*!< Reserved result type 2 (since 0.3.2) */
    S_RESULT_R3        = 13,    /*!< Reserved result type 3 (since 0.3.2) */
    S_RESULT_R4        = 14,    /*!< Reserved result type 4 (since 0.3.2) */
    S_RESULT_R5        = 15,    /*!< Reserved result type 5 (since 0.3.2) */
} result_t;
```

**Comment by shubham-mulay-BR** [comment]
Ok! Libsandbox wont work properly on Ubuntu 14.04 ?

**Comment by liuyu81** [comment]
Technically, `libsandbox` is neutral to Linux distributions. We haven't yet build a binary distribution for ubuntu 14.04, because previous long-term support version of ubuntu (i.e. 12.04 LTS) is only half-way in its 5-year lifecycle (i.e. between 2012 to 2017).

**Comment by shubham-mulay-BR** [comment]
Oh! So that might be the issue ! Will 12.04.5 LTS do ? or just 12.04?

**Comment by liuyu81** [comment]
I would recommend that you first run the testsuite of `libsandbox` on your 14.04 system. Result code between 1 and 7 (except `IE` and `BP`) usually indicate undesirable behaviors of _sandboxed_ programs, not `libsandbox` itself.

**Comment by shubham-mulay-BR** [comment]
Actually I m getting verdict 7 , actually it is not writing the output(stdout) to the targeted file! I m using 14.04, can you please help ?

**Comment by liuyu81** [comment]
Please elaborate. Are you using `libsandbox` from your own judge program or did you use a third-party program that invokes `libsandbox`. Are you using the Pythonic wrapper (aka. `pysandbox`) or the C library alone? Where did you see this `verdict 7` outcome?

**Comment by windtail** [comment]
I just run the testsuite on ubuntu 14.04.1, the result is **FAILED (failures=30, skipped=3)** 
and when i run the testsuite on ubuntu 12.04.4, the result is **OK (skipped=3)**

**Comment by shubham-mulay-BR** [comment]
I tried the same! On ubuntu 14.04 where I am getting verdict 7(Abnormal Termination), I am getting 1 as verdict in 12.04 i.e Okay!
Its better to use 12.04 only.
